global using System;
global using Avalonia;
global using Avalonia.Controls.ApplicationLifetimes;
global using Avalonia.Markup.Xaml;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using AvaloniaCollectionViewSample.Core;
global using AvaloniaCollectionViewSample.ViewModels;
global using AvaloniaCollectionViewSample.AvaloniaServices;
