FROM postgres:14

# 시스템의 기본 로케일을 C.UTF-8로 설정
# ENV LANG C.UTF-8
# ENV LANGUAGE ko_KR:ko
# ENV LC_ALL C.UTF-8

RUN apt-get update \
    && apt-get install -y vim

# PostgreSQL 환경 변수 설정
# ENV LANG ko_KR.UTF-8
# ENV LANGUAGE ko_KR:ko
# ENV LC_ALL ko_KR.UTF-8
