using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace cliAccessCompareCsv.Models.Tables
{
    internal enum EBAccessTables
    {
        AFCCSE_IVS_header,
        COME_DBME_header,
        COME_IME_header,
        COME_PPC_header,
        COME_SPC_header,
        DBME_IME_header,
        DBME_PPC_header,
        DBME_SPC_header,
        DBME_STE_header,
        DBME_VS_header,
        DGNSS_PPC_header,
        DGNSS_SPC_header,
        IAE_DBME_header,
        IAE_VS_header,
        IME_DBME_header,
        IME_MPE_header,
        IME_PPC_header,
        IME_SOC_header,
        IME_SPC_header,
        IME_STE_header,
        IME_VS_header,
        IVS_IME_header,
        KAOCE_IVS_header,
        MPE_DBME_header,
        MPE_IME_header,
        MPE_PPC_header,
        MPE_SPC_header,
        MPE_VS_header,
        PPC_COME_header,
        PPC_DBME_header,
        PPC_IME_header,
        PPC_MPE_header,
        PPC_SOC_header,
        PPC_SPC_header,
        PPC_STE_header,
        PPC_VS_header,
        SOC_DBME_header,
        SOC_IME_header,
        SOC_PPC_header,
        SOC_SPC_header,
        SOC_STE_header,
        SOC_VS_header,
        SPC_COME_header,
        SPC_DBME_header,
        SPC_IME_header,
        SPC_MPE_header,
        SPC_PPC_header,
        SPC_SOC_header,
        SPC_STE_header,
        SPC_VS_header,
        STE_DBME_header,
        STE_IME_header,
        STE_PPC_header,
        STE_SPC_header,
        VS_DBME_header,
        VS_IAE_header,
        VS_IME_header,
        VS_PPC_header,
        VS_SOC_header,
        VS_SPC_header,
        GCS_AVS_FLCC_header,
        GCS_AVS_header,
        GCS_AVS_IMC_header,
        GCS_DLS_header,
        GCS_EOIR_header,
        GCS_KP_header,
        GCS_SAR_header,
        GCS_TM_header,
        TOTAL
    }
}
